name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

pr:
  paths:
    include:
      - src/*
      - test/*
      
trigger:
  paths:
    include:
      - src/*
      - test/*

pool:
  vmImage: 'ubuntu-16.04'
  
variables:
  BuildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: 'Set version'
  inputs:
    filePath: 'scripts/build/SetAssemblyVersionOnBuildServer.ps1'

- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: PowerShell@2
  displayName: 'Create bot package'
  inputs:
    filePath: 'Create-BotPackage.ps1'
    arguments: '-OutputPath $(build.artifactstagingdirectory)/KlausPeterBot-package -Configuration $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/KlausPeterBot-package'
    ArtifactName: KlausPeterBot-package
